name: neoja_qa_app
description: A simple Q&A app with a Flask backend and Flutter frontend.
version: 1.0.0

environment:
  sdk: ">=3.6.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.0
  http: ^1.3.0
  socket_io_client: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
